# Generated by Django 5.1.2 on 2026-02-24 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('billing', 'Billing'), ('memo', 'Memo'), ('report', 'Report'), ('permit', 'Permit'), ('other', 'Other')], default='other', max_length=20)),
                ('division', models.CharField(choices=[('admin', 'Admin Division'), ('planning', 'Planning Division'), ('construction', 'Construction Division'), ('quality', 'Quality Division'), ('maintenance', 'Maintenance Division')], default='admin', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For Review'), ('processing', 'Processing'), ('open_issue', 'Open Issue'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_received_by_peo', models.DateField(blank=True, null=True)),
                ('date_released_to_admin', models.DateField(blank=True, null=True)),
                ('date_received_from_admin', models.DateField(blank=True, null=True)),
                ('date_released_to_accounting', models.DateField(blank=True, null=True)),
                ('billing_type', models.CharField(blank=True, max_length=120)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('revised_contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('period_covered', models.CharField(blank=True, max_length=120)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
