# Generated by Django 5.1.2 on 2026-02-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('site_instruction', 'Site Instruction'), ('ncr', 'NCR'), ('ded_package', 'DED Package'), ('billing_packet', 'Billing Packet'), ('work_order', 'Work Order'), ('report', 'Report'), ('contract', 'Contract'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For Review'), ('routed', 'Routed'), ('processing', 'Processing'), ('approved', 'Approved'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
