# Generated by Django 5.1.2 on 2026-02-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_constructionstatusreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConstructionStatusReport',
        ),
    ]
