# Generated by Django 5.1.2 on 2026-02-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_constructionstatusreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionStatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('mun', models.CharField(blank=True, max_length=50)),
                ('contractor', models.CharField(blank=True, max_length=255)),
                ('contract_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ntp_date', models.DateField(blank=True, null=True)),
                ('cd', models.IntegerField(blank=True, null=True)),
                ('original_expiry_date', models.DateField(blank=True, null=True)),
                ('additional_cd', models.IntegerField(blank=True, null=True)),
                ('revised_expiry_date', models.CharField(blank=True, max_length=120)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('revised_contract_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status_previous', models.CharField(blank=True, max_length=40)),
                ('status_current', models.CharField(blank=True, max_length=40)),
                ('percent_time_elapsed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('slippage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
