# Generated by Django 5.1.2 on 2026-02-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_constructionstatusreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fund', models.CharField(choices=[('20-development-fund', '20% Development Fund'), ('sef-fund', 'SEF')], default='20-development-fund', max_length=40)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('for_review', 'For Review')], default='approved', max_length=20)),
                ('fiscal_year', models.CharField(default='FY 2026', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
