# Generated by Django 5.1.2 on 2026-02-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_planningproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For Review'), ('approved', 'Approved'), ('for_bidding', 'For Bidding'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='approved', max_length=20),
        ),
    ]
