# Generated by Django 5.1.2 on 2026-02-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_document_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contractor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
